class4s: mv greeting() function into separate source file
This is not a time where I'd usually make a commit, since things are broken:


```
kais-mbp:cxx kai$ ./build.sh
hello.cxx: In function 'int main(int, char**)':
hello.cxx:17:3: error: 'greeting' was not declared in this scope
   17 |   greeting();
      |   ^~~~~~~~
```

This is a difference from C -- in C the compiler warned, but accepted
calling the unknown function `greeting()`.